name: Beamsical
favicon: null
layout_spectrum: 0.56115
typography_spectrum: 0.25125
title: Beamsical
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#007674'
    - '#76002b'
    - '#d65215'
    - '#d69800'
    - '#f7dcd1'
  brandStrength: 0.5
  lightness: 0.8217545084189624
  saturation: 0.23966597043909132
  rhythmicContrast: 0.19745629210956395
purpose: []
